### ISSUE TITLE
Cannot generate dataset

### ISSUE THREAD

**Issue by al-anatrini** [jorshi/spiegel#13]
I’m trying to recreate on my machine the FM sound match example. Unfortunately I’m not able to generate any dataset. I suppose is due to the “kNotImplemented, kResultFalse” messages. Would you have any suggestion? Thanks
![knotimplemented](https://user-images.githubusercontent.com/48674371/107273345-32130500-6a4f-11eb-896a-596d48d2a595.png)

**Comment by al-anatrini** [comment]
I believe I figure this out, it has to do with vst3 support. I'll try again with vst.

**Comment by jorshi** [comment]
@al-anatrini -- good to hear that you found the issue, would be great to get an updated version of renderman that supports vst3, but haven't had time to contribute to that. Did using the vst fix the problem for you?

**Comment by al-anatrini** [comment]
@jorshi yo using vst2 fixed the issue! Maybe it's worth mentioning that it seems renderman does not like vsts that use .wav files as resources. For example I built a custom plugin, which is a table-based synth. It works just fine in other contexts, but to match it with renderman, and thus spiegelib, I had to find a workaround. Nevertheless thanks for the amazing work :))

**Comment by jorshi** [comment]
@al-anatrini nice! Glad to hear that -- that is weird that renderman doesn't like vsts that use wav file as resources. I will make a note of that for sure, thanks for the heads up. And thanks for checking out spiegelib. Happy to receive any suggestions or PRs for this work if you have ideas for adding to it -- I haven't had much time with school being so busy, but am hoping to add some more in the future and link it with some ddsp stuff potentially! cheers
